apiVersion: apps/v1
kind: Deployment
metadata:
  name: development-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dev-app
  template:
    metadata:
      labels:
        app: dev-app
    spec:
      containers:
      - name: dev-container
        image: <your-region>-docker.pkg.dev/qwiklabs-gcp-02-1d96eb783bfe/my-repository/hello-cloudbuild-dev:<version>
        ports:
        - containerPort: 8080
